spring.datasource.url=jdbc:postgresql://autorack.proxy.rlwy.net:24063/railway
spring.datasource.username=postgres
spring.datasource.password=xgcTFfPmzBgWFaOGBSoTZvgDyCOCBuxI

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=

server.port=${PORT:8080}
server.address=0.0.0.0
