package com.sonixhr.service.payroll;

import com.sonixhr.dto.payroll.SurchargeSlabDTO;
import com.sonixhr.dto.payroll.TaxRegimeSlabConfigDTO;
import com.sonixhr.dto.payroll.TaxSlabRowDTO;
import com.sonixhr.entity.payroll.SurchargeSlab;
import com.sonixhr.entity.payroll.TaxRegimeSlabConfig;
import com.sonixhr.entity.payroll.TaxSlabRow;
import com.sonixhr.exceptions.BusinessException;
import com.sonixhr.exceptions.ResourceNotFoundException;
import com.sonixhr.repository.payroll.TaxRegimeSlabConfigRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class TaxSlabConfigService {

    private final TaxRegimeSlabConfigRepository repository;

    @Transactional(readOnly = true)
    public List<TaxRegimeSlabConfigDTO> getAllTaxSlabs() {
        return repository.findAll().stream()
                .map(this::convertToDTO)
                .collect(Collectors.toList());
    }

    @Transactional(readOnly = true)
    public TaxRegimeSlabConfigDTO getTaxSlabById(UUID id) {
        TaxRegimeSlabConfig entity = repository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Tax regime slab config not found"));
        return convertToDTO(entity);
    }

    @Transactional
    public TaxRegimeSlabConfigDTO createTaxSlab(TaxRegimeSlabConfigDTO dto) {
        log.info("Creating tax slab config for FY: {}, Regime: {}", dto.getFinancialYear(), dto.getRegime());
        
        // Validate uniqueness: financialYear + regime
        Optional<TaxRegimeSlabConfig> existing = repository.findByFinancialYearAndRegime(
                dto.getFinancialYear(), dto.getRegime()
        );
        if (existing.isPresent()) {
            throw new BusinessException("Tax regime slab configuration already exists for financial year: " 
                    + dto.getFinancialYear() + " and regime: " + dto.getRegime());
        }

        // Validate invariants: slabs must be valid (e.g. fromAmount < toAmount, ordered)
        validateSlabsInvariants(dto);

        TaxRegimeSlabConfig entity = convertToEntity(dto);
        // ID must be generated by server
        entity.setId(null);

        TaxRegimeSlabConfig saved = repository.save(entity);
        return convertToDTO(saved);
    }

    @Transactional
    public TaxRegimeSlabConfigDTO updateTaxSlab(UUID id, TaxRegimeSlabConfigDTO dto) {
        log.info("Updating tax slab config with ID: {}", id);
        
        TaxRegimeSlabConfig existing = repository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Tax regime slab config not found"));

        // Validate uniqueness if financialYear or regime changes
        if (!existing.getFinancialYear().equals(dto.getFinancialYear()) 
                || !existing.getRegime().equals(dto.getRegime())) {
            Optional<TaxRegimeSlabConfig> duplicate = repository.findByFinancialYearAndRegime(
                    dto.getFinancialYear(), dto.getRegime()
            );
            if (duplicate.isPresent() && !duplicate.get().getId().equals(id)) {
                throw new BusinessException("Tax regime slab configuration already exists for financial year: " 
                        + dto.getFinancialYear() + " and regime: " + dto.getRegime());
            }
        }

        // Validate invariants
        validateSlabsInvariants(dto);

        // Update fields, ignoring/rejecting server-managed ones like ID
        existing.setFinancialYear(dto.getFinancialYear());
        existing.setRegime(dto.getRegime());
        existing.setStandardDeduction(dto.getStandardDeduction());
        existing.setRebateLimit(dto.getRebateLimit());
        existing.setRebateMaxAmount(dto.getRebateMaxAmount());
        existing.setCessPercent(dto.getCessPercent());

        if (dto.getSlabs() != null) {
            existing.setSlabs(dto.getSlabs().stream()
                    .map(s -> TaxSlabRow.builder()
                            .fromAmount(s.getFromAmount())
                            .toAmount(s.getToAmount())
                            .ratePercent(s.getRatePercent())
                            .build())
                    .collect(Collectors.toList()));
        } else {
            existing.setSlabs(null);
        }

        if (dto.getSurchargeSlabs() != null) {
            existing.setSurchargeSlabs(dto.getSurchargeSlabs().stream()
                    .map(s -> SurchargeSlab.builder()
                            .threshold(s.getThreshold())
                            .ratePercent(s.getRatePercent())
                            .build())
                    .collect(Collectors.toList()));
        } else {
            existing.setSurchargeSlabs(null);
        }

        TaxRegimeSlabConfig saved = repository.save(existing);
        return convertToDTO(saved);
    }

    @Transactional
    public void deleteTaxSlab(UUID id) {
        log.info("Deleting tax slab config with ID: {}", id);
        TaxRegimeSlabConfig existing = repository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Tax regime slab config not found"));
        repository.delete(existing);
    }

    private void validateSlabsInvariants(TaxRegimeSlabConfigDTO dto) {
        if (dto.getSlabs() != null) {
            for (TaxSlabRowDTO slab : dto.getSlabs()) {
                if (slab.getFromAmount() == null) {
                    throw new BusinessException("Slab fromAmount cannot be null");
                }
                if (slab.getRatePercent() == null) {
                    throw new BusinessException("Slab ratePercent cannot be null");
                }
                if (slab.getToAmount() != null && slab.getFromAmount().compareTo(slab.getToAmount()) > 0) {
                    throw new BusinessException("Slab fromAmount cannot be greater than toAmount");
                }
            }
        }
    }

    private TaxRegimeSlabConfigDTO convertToDTO(TaxRegimeSlabConfig entity) {
        if (entity == null) return null;
        return TaxRegimeSlabConfigDTO.builder()
                .id(entity.getId())
                .financialYear(entity.getFinancialYear())
                .regime(entity.getRegime())
                .standardDeduction(entity.getStandardDeduction())
                .rebateLimit(entity.getRebateLimit())
                .rebateMaxAmount(entity.getRebateMaxAmount())
                .cessPercent(entity.getCessPercent())
                .slabs(entity.getSlabs() != null ? entity.getSlabs().stream()
                        .map(s -> TaxSlabRowDTO.builder()
                                .fromAmount(s.getFromAmount())
                                .toAmount(s.getToAmount())
                                .ratePercent(s.getRatePercent())
                                .build())
                        .collect(Collectors.toList()) : null)
                .surchargeSlabs(entity.getSurchargeSlabs() != null ? entity.getSurchargeSlabs().stream()
                        .map(s -> SurchargeSlabDTO.builder()
                                .threshold(s.getThreshold())
                                .ratePercent(s.getRatePercent())
                                .build())
                        .collect(Collectors.toList()) : null)
                .build();
    }

    private TaxRegimeSlabConfig convertToEntity(TaxRegimeSlabConfigDTO dto) {
        if (dto == null) return null;
        return TaxRegimeSlabConfig.builder()
                .id(dto.getId())
                .financialYear(dto.getFinancialYear())
                .regime(dto.getRegime())
                .standardDeduction(dto.getStandardDeduction())
                .rebateLimit(dto.getRebateLimit())
                .rebateMaxAmount(dto.getRebateMaxAmount())
                .cessPercent(dto.getCessPercent())
                .slabs(dto.getSlabs() != null ? dto.getSlabs().stream()
                        .map(s -> TaxSlabRow.builder()
                                .fromAmount(s.getFromAmount())
                                .toAmount(s.getToAmount())
                                .ratePercent(s.getRatePercent())
                                .build())
                        .collect(Collectors.toList()) : null)
                .surchargeSlabs(dto.getSurchargeSlabs() != null ? dto.getSurchargeSlabs().stream()
                        .map(s -> SurchargeSlab.builder()
                                .threshold(s.getThreshold())
                                .ratePercent(s.getRatePercent())
                                .build())
                        .collect(Collectors.toList()) : null)
                .build();
    }
}
